---
- name: installing key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
    validate_certs : False

- name: adding repository
  apt_repository:
    repo: deb {{ item.repo }} {{ item.add }}
    state: present

- name: apt update
  become: yes
  apt:
    update_cache: yes
