# - name: ensure php5-fpm cgi.fix_pathinfo=0
#   become: yes
#   lineinfile: dest=/etc/php5/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
#   notify:
#     - restart php5-fpm

# - name: enable php5 mcrypt module
#   become: yes
#   shell: php5enmod mcrypt
#   args:
#     creates: /etc/php5/cli/conf.d/20-mcrypt.ini

- name: create /var/www/ directory
  become: yes
  file: dest=/var/www/ state=directory owner=www-data group=www-data mode=0700
  notify:
    - restart php5-fpm
